# Generated by Django 2.1.4 on 2019-01-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181228_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='equipement',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
