# Generated by Django 2.1.4 on 2019-01-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190104_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='equipement',
            field=models.ImageField(blank=True, null=True, upload_to='equipements/'),
        ),
    ]
