# Generated by Django 2.1.4 on 2019-01-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190116_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superviser',
            name='auteur',
        ),
    ]
